### ISSUE TITLE
Certify Colectiva as a 501(c)(3) with Tech Soup

### ISSUE THREAD

**Issue by ErrorsAndGlitches** [ColectivaLegal/waisn-tech-team#5]
# Problem

To get AWS credits through Tech Soup, Colectiva needs to be 501(c)(3) certified.

# Solution

Provide the necessary documentation and go through the certification process with Tech Soup.

# Other

This blocks: Issue https://github.com/ColectivaLegal/waisn-tech-team/issues/4

**Comment by jordanhom** [comment]
Quick update:

Next steps are to submit an IRS document verifying Colectiva's non-profit status.
Victoria emailed me the document. I will forward the document to them today (Jan 10) when I am able.

**Comment by jordanhom** [comment]
Colectiva's 501c3 determination letter from the IRS has been submitted to TechSoup.

I've asked their support how long it may take for our account to be fully qualified. I will update this ticket when I get the info.

**Comment by jordanhom** [comment]
Our account on TechSoup is set up and Colectiva is considered qualified 501c3 non profit! I think we're good to go here.
